version: 2

updates:
  # Update uv packages
  - package-ecosystem: uv
    directory: /
    open-pull-requests-limit: 10

    # Wait 7 days after release before raising an update
    cooldown:
      default-days: 7

    # Group all uv package updates into one PR per run
    groups:
      uv:
        patterns:
          - '*'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct pyproject.toml updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Wait 7 days after release before raising an update
    cooldown:
      default-days: 7

    # Group all GitHub Actions updates into one PR per run
    groups:
      github-actions:
        patterns:
          - '*'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
